### ISSUE TITLE
value of m_stop_reson is always empty when handling some commands

### ISSUE THREAD

**Issue by Meik152** [machineware-gmbh/vcml#42]
Hey,

in the vspserver the `m_stop_reason` is returned when the server is handling a resume command. But the value of `m_stop_reason` is cleared by the function `resume_simulation()` which is called before. So the value of `m_stop_reason` is always an empty string. This behavior is also appearing in the function`handle_step()`.

https://github.com/machineware-gmbh/vcml/blob/main/src/vcml/debugging/vspserver.cpp#L171-L172
https://github.com/machineware-gmbh/vcml/blob/main/src/vcml/debugging/vspserver.cpp#L188-L189

Shouldn't the value be saved before calling `resume_simulation()`?

Meik

**Comment by janweinstock** [comment]
Thanks for the report. The stop reason used to be reported back when `step` and `resume` were still blocking until the simulation was paused again. This is no longer the case, since we use `status` to poll if the simulation is running or not. Consequently, the stop reason should not be reported for the two former commands. If have pushed a fix for this.
