### ISSUE TITLE
mwr is not installed during vcml installation

### ISSUE THREAD

**Issue by mohamed** [machineware-gmbh/vcml#44]
`vcml` downloads a copy of `mwr` while building `vcml`. However, when the user invokes `make install` under `vcml`, `mwr` is not installed. This results in an compile error later when the user tries to use `vcml` since `mwr` is not installed. I see two fixes:

1. Modify the build script of `vcml` to install `mwr` with it when the user does `make install` in `vcml`
2. Decouple the two libraries and list `mwr` as a prerequisite for `vcml` (just like `libelf`)

**Comment by janweinstock** [comment]
Hi Mohamed,

the functionality to install subprojects has been disabled intentionally (see [here](https://github.com/machineware-gmbh/mwr/blob/edff63aa6ba04adda6d2d0daa29d85e8514f56b6/CMakeLists.txt#L71)). Since `vcml` comes as a static c++ library, we prefer to not install it locally but rather build it in one go with the rest of the simulator, where we include all dependencies from a top-level `CMakeLists.txt` and use the same compiler, toolchain and flags for everything.

If you want the individual libraries and headers to be installed locally, you need to clone, build and install the projects separately. Once you have cloned `mwr`, export its source directory as `MWR_HOME`. The build process of `vcml` will then use your local copy and not redownload `mwr`. You can then run `make install` for each project separately.
