### ISSUE TITLE
vcml tlm socket doesn't support multiple bound

### ISSUE THREAD

**Issue by maestrosoft** [machineware-gmbh/vcml#99]
VCML doesn't support multiple binding for VCML TLM sockets. The template to create the number of bindings is set to 1.

**Comment by janweinstock** [comment]
Hello maestrosoft,
VCML currently supports only single binding for TLM sockets because we follow the design of the `simple_initiator_socket` and `simple_target_socket` classes from SystemC, which limit the number of bindings to one. This is by design and aligns with how SystemC handles socket connections. To support multiple bindings, a custom implementation would be required, but the current setup meets most standard use cases. Could you explain your use case so we can better understand what you're trying to accomplish?
